[package]
name = "aries_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odbc-api = "0.29.1"
anyhow = "1.0.44"
csv = "1.1.6"